# Generated by Django 3.0.6 on 2020-05-29 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=200)),
                ('last_name', models.CharField(help_text='Last name', max_length=200)),
                ('address', models.TextField()),
                ('total_working_experience', models.PositiveIntegerField(default=0, help_text='Total working experience')),
                ('phone_no', phone_field.models.PhoneField(help_text='Mobile number', max_length=31)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('about_you', models.TextField(help_text='Brief intro')),
                ('image', models.ImageField(help_text='User Image', upload_to='user')),
                ('linkedin', models.CharField(help_text='Linkedin username', max_length=200)),
                ('facebook', models.CharField(help_text='Facebook username', max_length=200)),
                ('github', models.CharField(help_text='Github username', max_length=200)),
                ('twitter', models.CharField(help_text='Twitter username', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User data',
                'verbose_name_plural': 'User data',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(help_text='workflow', max_length=200)),
                ('user_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_workflow', to='dashboard.UserData')),
            ],
            options={
                'verbose_name': 'workflow',
                'verbose_name_plural': 'workflow',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='skill', max_length=200)),
                ('user_skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='dashboard.UserData')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='project_name', max_length=200)),
                ('project_description', models.TextField(help_text='brief intro to project')),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project', to='dashboard.UserData')),
            ],
            options={
                'verbose_name': 'certificates',
                'verbose_name_plural': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.TextField(help_text='interest')),
                ('user_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interest', to='dashboard.UserData')),
            ],
            options={
                'verbose_name': 'interest',
                'verbose_name_plural': 'interest',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Company position', max_length=200)),
                ('name', models.CharField(help_text='Company name', max_length=200)),
                ('joined_at', models.DateField(null=True)),
                ('worked_till', models.DateField(null=True)),
                ('description', models.TextField(help_text='Work Description')),
                ('user_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_experience', to='dashboard.UserData')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(help_text='University name', max_length=200)),
                ('course', models.CharField(help_text='Course', max_length=200)),
                ('joined_at', models.DateField(null=True)),
                ('left_at', models.DateField(null=True)),
                ('cgpa', models.CharField(help_text='CGPA', max_length=200)),
                ('user_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to='dashboard.UserData')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificates', models.CharField(help_text='certificates', max_length=200)),
                ('user_certificates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_certificates', to='dashboard.UserData')),
            ],
            options={
                'verbose_name': 'certificates',
                'verbose_name_plural': 'certificates',
            },
        ),
    ]
