# Generated by Django 3.0.6 on 2020-05-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='count',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_types',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Recruiter', 'Recruiter')], default='Candidate', max_length=10),
        ),
    ]
